- db/seeds.ts
- src/core/components/pricing-grid/PricingGrid.tsx
- src/pages/index.tsx
- src/styles/Home.module.css
- tailwind.config.js
> feat: PricingGrid

- src/core/components/pricing-grid/PricingGrid.tsx
- src/pages/checklists/my-basic-checklist.tsx
- src/pages/index.tsx
- src/pages/settings/index.tsx
- src/styles/Home.module.css
> feat: better benefits

- db/checklists.json
- db/migrations/20230719034635_checklist_item_detail_text/migration.sql
- db/migrations/20230719035112_links_for_checklist_items/migration.sql
- db/migrations/20230719052022_versioned_checklist_items/migration.sql
- db/schema.prisma
- db/seeds.ts
- package.json
- scripts/backupChecklists.js
- scripts/deleteUnusedChecklistItems.js
- src/pages/checklists/my-premium-checklist.tsx
- src/pages/index.tsx
- src/pages/settings/index.tsx
- src/users/hooks/useSubscriptionLevel.ts
- src/users/queries/getCurrentUser.ts
> better checklist items

- db/migrations/20230719190420_more_email_fields_and_subscription_type/migration.sql
- db/schema.prisma
- scripts/one-offs/ensureUserSubscriptions.js
- src/auth/mutations/signup.ts
- src/users/queries/getCurrentUser.ts
and subscription type
closes #59
> feat: more email fields

- package-lock.json
- package.json
- src/pages/_app.tsx
- src/pages/_document.tsx
> fix: google analytics

- src/core/components/page-wrapper/LadderlyPageWrapper.tsx
- src/pages/about.tsx
- src/pages/privacy-policy.tsx
- src/styles/Home.module.css
> feat: init about and priv policy

- .github/workflows/ci.yml
> chore: discord bot

- src/pages/_app.tsx
- src/user-checklists/components/UserChecklistQueryHandler.tsx
- src/user-checklists/mutations/createUserChecklist.ts
- src/user-checklists/queries/getLatestUserChecklistByName.ts
- src/user-checklists/schemas.ts
1. closes #120 
2. improves error page style
> fix: show userchecklist on safari

- src/core/components/page-wrapper/TopNavRight.tsx
Added chevron flipping when selected to show what is currently expanded.
> feat: toggle chevron when dropdown clicked

- package-lock.json
- package.json
- src/core/components/page-wrapper/LadderlyPageWrapper.tsx
- src/core/layouts/Layout.tsx
- src/pages/blog/2023-12-01-top-job-boards.md
- src/pages/blog/[slug].tsx
- src/pages/settings/index.tsx
and the jobs board blog article!
> feat: external blog links and canonical urls

- db/checklists.json
- src/pages/blog/2023-12-25-arias-tale.md
shout out to Annie from TikTok for the call out
closes #144
> fix: blog URL

- db/migrations/20240111015249_init_total_contributions/migration.sql
- db/migrations/20240111022632_unique_subscription_by_type/migration.sql
- db/migrations/20240111030957_rm_unique_contrib_per_subs/migration.sql
- db/schema.prisma
- scripts/tableScraperStripe.js
- scripts/updateUserSubscriptionsFromStripe.js
- src/pages/community/hall-of-fame/index.tsx
- src/pages/community/index.tsx
- src/users/queries/getUsers.ts
closes #76 
the hall of fame is a leaderboard of awesomeness. the people named there are objectively the most awesome
today, it is out highest donors (that check the box in settings allowing their public recognition)
in the future we will also support store purchases as a dropdown/filter/category of fame, and also code contributions
> feat: init hall of fame

- public/robots.txt
partial https://github.com/Vandivier/ladderly-3/issues/156
> feat: robots

- src/pages/blog/2024-02-11-essentials-of-html.md
- src/pages/blog/2024-02-12-resume-optimization.md
> feat: essentials of html article

- src/user-checklists/queries/getLatestUserChecklistByName.ts
> fix: get latest user checklist by name

- public/sitemap.xml
- src/pages/blog/2023-12-01-top-job-boards.md
- src/pages/blog/2024-01-23-leetcode-solutions.md
- src/pages/privacy-policy.tsx
closes #207 
closes #210 
1. improves the job board article to mention job titles under search, skill specializations, another job board, and job board links.
2. links to the YouTube leetcode solutions playlists on the article 7 for leetcode solutions
> docs: enhanced job board article

- docs/SETUP.md
Added documentation with steps, faq and troubleshooting for initial setup of ladderly.io.
> Create Initial Setup Documentation. 

- README.md
- docs/SETUP.md
closes https://github.com/Vandivier/ladderly-3/issues/224
> docs: minor revisions

- src/app/user-checklists/components/UserChecklistQueryHandler.tsx
- src/core/utils/parsing.ts
> fix: parse url

- src/app/top-honors/[type]/page.tsx
- src/app/top-honors/components/TopHonorsContent.tsx
- src/app/top-honors/page.tsx
- src/app/vote/[type]/page.tsx
- src/app/vote/components/VotePageContent.tsx
- src/app/vote/page.tsx
- src/votable/utils.ts
and quick links to vote from top honors page and vice versa
partials #287 
kudos to Sai Bhavanasi for the feedback
> feat: honor type pages

- blitz-app/src/app/questions/ClientQuestionsPage.tsx
- blitz-app/src/app/questions/[questionId]/QuestionDetails.tsx
- blitz-app/src/app/questions/components/AskQuestionForm.tsx
- blitz-app/src/app/questions/components/PleaseLoginComponent.tsx
- blitz-app/src/app/questions/queries/getQuestion.ts
- blitz-app/src/app/questions/queries/getQuestions.ts
- blitz-app/src/app/questions/utils.ts
> feat: PleaseLoginComponent

- blitz-app/scripts/youtube-transcriber/.env.template
- blitz-app/scripts/youtube-transcriber/manage_playlist.py
> feat: better env var name

- blitz-app/src/app/home/HomePageContent.tsx
- blitz-app/src/app/home/HomePageSkeleton.tsx
- blitz-app/src/app/styles/Home.module.css
> feat: testimonial widget

- blitz-app/src/app/home/HomePageContent.tsx
- blitz-app/src/core/components/page-wrapper/TopNav.tsx
- blitz-app/src/core/components/page-wrapper/TopNavSubmenu.tsx
- blitz-app/src/core/theme/ThemeUtils.ts
> fix: subnav dark mode style

- blitz-app/src/app/mobile-menu/page.tsx
- blitz-app/src/app/perks/page.tsx
- blitz-app/src/core/components/page-wrapper/TopNavRight.tsx
- ladderly-io/src/app/core/components/page-wrapper/TopNavRight.tsx
- ladderly-io/src/app/perks/page.tsx
closes #338 
adds a perks feature where people can obtain a referral code for recommended services
> feat: perks!

- ladderly-io/src/app/community/ClientCommunityPage.tsx
- ladderly-io/src/app/core/components/pricing-grid/PricingGrid.tsx
- ladderly-io/src/server/api/routers/user.ts
> fix: free premium text margin

- ladderly-io/scripts/deleteUser.ts
- ladderly-io/src/app/community/ClientCommunityPage.tsx
- ladderly-io/src/app/core/components/pricing-grid/PricingGrid.tsx
- ladderly-io/src/app/home/HomePageContent.tsx
- ladderly-io/src/app/settings/components/SettingsFormWrapper.tsx
- ladderly-io/src/server/auth.ts
after user settings update
and create sso user if not exist
> feat: no need to refresh

- ladderly-io/src/app/community/ClientCommunityPage.tsx
- ladderly-io/src/app/community/SearchProfiles.tsx
- ladderly-io/src/app/community/page.tsx
- ladderly-io/src/app/core/components/SmallCard.tsx
- ladderly-io/src/server/api/routers/user.ts
> feat: search profiles

- ladderly-io/prisma/schema.prisma
- ladderly-io/src/app/api/webhooks/stripe/route.ts
by updating instead of creating on change
closes #379
> fix: subscription unique constraint

- ladderly-io/src/app/blog/2023-11-25-leetcode-kata.md
- ladderly-io/src/app/blog/[slug]/getBlogPost.ts
- ladderly-io/src/app/blog/[slug]/page.tsx
closes https://github.com/Vandivier/ladderly-3/issues/267
closes https://github.com/Vandivier/ladderly-3/issues/218
closes https://github.com/Vandivier/ladderly-3/issues/246
partials https://github.com/Vandivier/ladderly-3/issues/363
> docs: 218 better kata

- ladderly-io/src/app/blog/2024-05-31-networking-tips.md
- ladderly-io/src/app/blog/2025-01-20-social-networking-scripts.md
> docs: resume floater script

- ladderly-io/public/sitemap.xml
- ladderly-io/src/app/blog/2025-02-07-ladderly-chat-ai.md
- ladderly-io/src/app/general-chat/page.tsx
- ladderly-io/src/app/home/HomePageContent.tsx
> 397 chatbot

- .vscode/extensions.json
- ladderly-io/.gitignore
- ladderly-io/package-lock.json
- ladderly-io/package.json
- ladderly-io/src/app/api/webhooks/stripe/route.ts
- ladderly-io/src/app/core/components/pricing-grid/PricingGrid.tsx
- ladderly-io/tests/app/api/webhooks/stripe/route.test.ts
- ladderly-io/tests/app/page.test.tsx
- ladderly-io/vitest.config.ts
1. fix stripe webhook
2. test w vitest
3. gitignore and other minor changes
closes #411
> test: stripe webhook

- .github/workflows/tests.yml
> chore: gha cov gate

- ladderly-io/public/sitemap.xml
- ladderly-io/src/app/blog/2023-10-01-quality-course-and-projects.md
- ladderly-io/src/app/blog/2023-11-25-leetcode-kata.md
- ladderly-io/src/app/blog/2023-12-01-top-job-boards.md
- ladderly-io/src/app/blog/2023-12-25-arias-tale.md
- ladderly-io/src/app/blog/2024-01-20-hardware.md
- ladderly-io/src/app/blog/2024-01-23-leetcode-solutions.md
- ladderly-io/src/app/blog/2024-02-11-essentials-of-html.md
- ladderly-io/src/app/blog/2024-02-12-resume-optimization.md
- ladderly-io/src/app/blog/2024-02-16-user-settings.md
- ladderly-io/src/app/blog/2024-04-20-hook-fundamentals.md
- ladderly-io/src/app/blog/2024-05-31-networking-tips.md
- ladderly-io/src/app/blog/2024-06-12-selecting-your-next-skill.md
- ladderly-io/src/app/blog/2024-07-31-impact-accounting.md
- ladderly-io/src/app/blog/2024-08-04-no-cover-letters.md
- ladderly-io/src/app/blog/2025-01-20-social-networking-scripts.md
- ladderly-io/src/app/blog/2025-01-21-ai-first-curriculum.md
- ladderly-io/src/app/blog/2025-01-22-endorsed-communities.md
- ladderly-io/src/app/blog/2025-02-07-ladderly-chat-ai.md
- ladderly-io/src/app/blog/2025-02-24-behavioral-interviews.md
- ladderly-io/src/app/blog/2025-02-25-ballparking.md
> docs: new articles

- .github/workflows/tests.yml
- ladderly-io/.gitignore
- ladderly-io/next.config.js
- ladderly-io/package.json
- ladderly-io/src/app/core/components/page-wrapper/TopNavSubmenu.tsx
- ladderly-io/src/app/core/components/pricing-grid/PricingGrid.tsx
- ladderly-io/src/app/mobile-menu/MobileMenuContent.tsx
- ladderly-io/tests/app/core/components/pricing-grid/PricingGrid.test.tsx
- ladderly-io/tests/app/home/HomePageContent.test.tsx
- ladderly-io/tests/app/page.test.tsx
- ladderly-io/tests/setup.ts
- ladderly-io/tsconfig.json
- ladderly-io/vitest.config.ts
> 421 consistent ux

- ladderly-io/src/app/blog/2025-02-24-behavioral-interviews.md
- ladderly-io/src/app/checklists/my-basic-checklist/ClientBasicChecklist.tsx
- ladderly-io/src/app/checklists/my-basic-checklist/page.tsx
- ladderly-io/src/app/checklists/my-premium-checklist/ClientPremiumChecklist.tsx
- ladderly-io/src/app/checklists/my-premium-checklist/page.tsx
> fix: missing space

- ladderly-io/src/app/perks/page.tsx
> feat: formation perk

- ladderly-io/src/app/core/components/pricing-grid/PricingGrid.tsx
- ladderly-io/src/app/core/components/pricing-grid/ReimbursmentLetterLink.tsx
> feat: track clicks on reimbursement letter

- Makefile
- ladderly-io/scripts/python/copilot-instructions.txt
- ladderly-io/src/app/blog/2024-02-12-resume-optimization.md
- ladderly-io/src/app/blog/2025-02-24-behavioral-interviews.md
and makefile
closes #429 
closes #448
> feat: makefile

- ladderly-io/prisma/schema.prisma
- ladderly-io/public/sitemap.xml
- ladderly-io/scripts/python/copilot-instructions.txt
- ladderly-io/src/app/copilot/page.tsx
- ladderly-io/src/app/core/components/page-wrapper/MenuProvider.tsx
- ladderly-io/src/app/core/components/page-wrapper/TopNavRight.tsx
- ladderly-io/src/app/core/components/page-wrapper/TopNavSubmenu.tsx
- ladderly-io/src/app/home/HomePageContent.tsx
- ladderly-io/src/app/job-search/ClientJobSearchPage.tsx
- ladderly-io/src/app/job-search/CreateJobSearchModal.tsx
- ladderly-io/src/app/job-search/JobSearchActiveSpan.tsx
- ladderly-io/src/app/job-search/JobSearchList.tsx
- ladderly-io/src/app/job-search/[id]/AddJobApplicationModal.tsx
- ladderly-io/src/app/job-search/[id]/JobSearchDetails.tsx
- ladderly-io/src/app/job-search/[id]/page.tsx
- ladderly-io/src/app/job-search/job-post/[id]/JobPostDetails.tsx
- ladderly-io/src/app/job-search/job-post/[id]/page.tsx
- ladderly-io/src/app/job-search/page.tsx
- ladderly-io/src/app/mobile-menu/MobileMenuContent.tsx
- ladderly-io/src/app/mobile-menu/MobileMenuDropdowns.tsx
- ladderly-io/src/server/api/root.ts
- ladderly-io/src/server/api/routers/jobSearch.ts
> feat: job search entity

- ladderly-io/package-lock.json
- ladderly-io/package.json
- ladderly-io/prisma/schema.prisma
- ladderly-io/prisma/seed-utils/seedLeetcodeChecklist.ts
- ladderly-io/prisma/seed-utils/seedVotables.ts
- ladderly-io/prisma/seeds.ts
- ladderly-io/public/sitemap.xml
- ladderly-io/src/app/core/components/page-wrapper/TopNavSubmenu.tsx
- ladderly-io/src/app/leetcode-tool/LeetCodeFilterControl.tsx
- ladderly-io/src/app/leetcode-tool/LeetCodeList.tsx
- ladderly-io/src/app/leetcode-tool/page.tsx
> feat: leetcode tool

- ladderly-io/src/app/blog/2025-04-18-time-management.md
> docs: time mgmt article

- ladderly-io/src/app/core/components/LadderlyPitch.tsx
- ladderly-io/src/app/journal/CreateJournalEntryForm.tsx
- ladderly-io/src/app/journal/JournalEntryList.tsx
- ladderly-io/src/app/leetcode-tool/CompletionStatusFilter.tsx
- ladderly-io/src/app/leetcode-tool/LeetCodeList.tsx
- ladderly-io/src/app/leetcode-tool/RandomProblemRecommendation.tsx
- ladderly-io/src/app/leetcode-tool/page.tsx
- ladderly-io/src/server/api/routers/journal.ts
> fix: dark mode text legibility

- ladderly-io/src/app/blog/2025-05-01-lsg2-learnings.md
closes #503 
honestly i threw rough notes to cursor auto for this so it could use more meticulous review
> 503 lsg2 initial thoughts

- ladderly-io/src/app/blog/2025-05-01-lsg2-learnings.md
> docs: How to Join a Cohort

- ladderly-io/src/app/journal/StoryGenerator.tsx
> Fix: Content generator overflow

- ladderly-io/public/sitemap.xml
- ladderly-io/src/app/(auth)/signup/interview-prep/page.tsx
- ladderly-io/src/app/(auth)/signup/research-backed/page.tsx
- ladderly-io/src/app/(auth)/signup/technical-prep/page.tsx
- ladderly-io/src/app/(auth)/signup/wellness/page.tsx
- ladderly-io/src/app/core/components/page-wrapper/SignupPageWrapper.tsx
- ladderly-io/src/app/journal/CreateJournalEntryForm.tsx
- ladderly-io/src/app/journal/StoryGenerator.tsx
- ladderly-io/src/app/journal/WeeklyEntryCountIndicator.tsx
- ladderly-io/src/app/journal/page.tsx
- ladderly-io/src/app/page.tsx
- ladderly-io/src/server/api/routers/journal.ts
> feat: better journaling landing pages

- Makefile
- ladderly-io/src/app/blog/2025-05-11-design-docs.md
> docs: project success through design docs

- ladderly-io/src/app/blog/2025-05-11-design-docs.md
> docs: more on how to use

- ladderly-io/src/app/perks/page.tsx
> feat: rm robinhood

- .github/workflows/stale.yml
> feat: add stale PR management workflow

- ladderly-io/prisma/schema.prisma
- ladderly-io/src/app/community/ClientCommunityPage.tsx
- ladderly-io/src/app/core/components/page-wrapper/TopNavRight.tsx
- ladderly-io/src/app/job-tracker/JobSearchList.tsx
- ladderly-io/src/app/job-tracker/[id]/JobTrackerDetails.tsx
- ladderly-io/src/app/job-tracker/[id]/components/JobPostList.tsx
- ladderly-io/src/app/journal/ReminderSettings.tsx
- ladderly-io/src/app/leetcode-tool/CompletionStatusFilter.tsx
- ladderly-io/src/app/leetcode-tool/LeetCodeFilterControl.tsx
- ladderly-io/src/app/leetcode-tool/LeetCodeList.tsx
- ladderly-io/src/app/leetcode-tool/RandomProblemRecommendation.tsx
- ladderly-io/src/pages/api/send-journal-reminders.ts
- ladderly-io/src/server/api/routers/journal.ts
- ladderly-io/src/server/auth.ts
- ladderly-io/src/server/mailers/journalReminderMailer.ts
> feat: journal email reminders

- ladderly-io/scripts/python/leetcode-problems/leetcode-ladderly-expanded-kata.json
- ladderly-io/src/app/blog/2023-11-25-leetcode-kata.md
> 554 better binary search

- ladderly-io/prisma/seeds/votables.json
- ladderly-io/src/app/blog/2023-10-01-quality-course-and-projects.md
- ladderly-io/src/app/core/components/page-wrapper/SignupPageWrapper.tsx
> style: rm top mobile padding

- ladderly-io/prisma/seed-utils/seedLeetcodeChecklist.ts
- ladderly-io/scripts/python/enrich_leetcode_difficulty.py
- ladderly-io/scripts/python/leetcode-problems/unified-leetcode-problems.json
- ladderly-io/scripts/python/pyproject.toml
- ladderly-io/scripts/python/uv.lock
- ladderly-io/src/app/leetcode-tool/DifficultyFilter.tsx
- ladderly-io/src/app/leetcode-tool/LeetCodeList.tsx
- ladderly-io/src/app/leetcode-tool/page.tsx
> feat: DifficultyFilter

- ladderly-io/src/app/blog/2023-11-25-leetcode-kata.md
- ladderly-io/src/app/blog/2024-05-31-networking-tips.md
partials https://github.com/Vandivier/ladderly-3/issues/561
partials https://github.com/Vandivier/ladderly-3/issues/551
> docs: Ladderly 360

- ladderly-io/src/app/blog/2025-08-31-backtracking.md
> blog: backtracking time complexity
